USE [master]
GO
/****** Object:  Database [EFViewAndManyToMany]    Script Date: 1/14/2020 20:31:21 ******/
CREATE DATABASE [EFViewAndManyToMany]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EFViewAndManyToMany', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\EFViewAndManyToMany.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EFViewAndManyToMany_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\EFViewAndManyToMany_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [EFViewAndManyToMany] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EFViewAndManyToMany].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EFViewAndManyToMany] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET ARITHABORT OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EFViewAndManyToMany] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EFViewAndManyToMany] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EFViewAndManyToMany] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EFViewAndManyToMany] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET RECOVERY FULL 
GO
ALTER DATABASE [EFViewAndManyToMany] SET  MULTI_USER 
GO
ALTER DATABASE [EFViewAndManyToMany] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EFViewAndManyToMany] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EFViewAndManyToMany] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EFViewAndManyToMany] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EFViewAndManyToMany] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'EFViewAndManyToMany', N'ON'
GO
ALTER DATABASE [EFViewAndManyToMany] SET QUERY_STORE = OFF
GO
USE [EFViewAndManyToMany]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [EFViewAndManyToMany]
GO
/****** Object:  Table [dbo].[Post]    Script Date: 1/14/2020 20:31:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Post](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AuthorId] [int] NOT NULL,
	[Content] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Post] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[PostView]    Script Date: 1/14/2020 20:31:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[PostView] AS
SELECT *
FROM [Post]
GO
/****** Object:  Table [dbo].[Author]    Script Date: 1/14/2020 20:31:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Author](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Author] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Post_Tag]    Script Date: 1/14/2020 20:31:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Post_Tag](
	[PostId] [int] NOT NULL,
	[TagId] [int] NOT NULL,
 CONSTRAINT [PK_Post_Tag] PRIMARY KEY CLUSTERED 
(
	[PostId] ASC,
	[TagId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tag]    Script Date: 1/14/2020 20:31:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tag](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Tag] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Author] ON 

INSERT [dbo].[Author] ([Id], [Name]) VALUES (1, N'Bob')
SET IDENTITY_INSERT [dbo].[Author] OFF
SET IDENTITY_INSERT [dbo].[Post] ON 

INSERT [dbo].[Post] ([Id], [AuthorId], [Content]) VALUES (1, 1, N'Stuff')
SET IDENTITY_INSERT [dbo].[Post] OFF
INSERT [dbo].[Post_Tag] ([PostId], [TagId]) VALUES (1, 1)
SET IDENTITY_INSERT [dbo].[Tag] ON 

INSERT [dbo].[Tag] ([Id], [Name]) VALUES (1, N'Tag')
SET IDENTITY_INSERT [dbo].[Tag] OFF
ALTER TABLE [dbo].[Post]  WITH CHECK ADD  CONSTRAINT [FK_Post_Author] FOREIGN KEY([AuthorId])
REFERENCES [dbo].[Author] ([Id])
GO
ALTER TABLE [dbo].[Post] CHECK CONSTRAINT [FK_Post_Author]
GO
ALTER TABLE [dbo].[Post_Tag]  WITH CHECK ADD  CONSTRAINT [FK_Post_Tag_Post] FOREIGN KEY([PostId])
REFERENCES [dbo].[Post] ([Id])
GO
ALTER TABLE [dbo].[Post_Tag] CHECK CONSTRAINT [FK_Post_Tag_Post]
GO
ALTER TABLE [dbo].[Post_Tag]  WITH CHECK ADD  CONSTRAINT [FK_Post_Tag_Tag] FOREIGN KEY([TagId])
REFERENCES [dbo].[Tag] ([Id])
GO
ALTER TABLE [dbo].[Post_Tag] CHECK CONSTRAINT [FK_Post_Tag_Tag]
GO
USE [master]
GO
ALTER DATABASE [EFViewAndManyToMany] SET  READ_WRITE 
GO
